# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbd46be69cb3e2b1cec9f9cb4966b478515513b49141ec38b9ca42dadcdaf6f788b061df458ad8fb27b52243c3c61984bb31b5c7f11a78bcb76f7f3f9bf234da

test:
  secret_key_base: 7d4432e008ca5856d98c3600525d95c165a59ea7cba9191b3cd7e782479dfca9020086c7930e8bcb870627ddcb58eff1710fa8e4e819a33aa311c95ed92301ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
